// GENERATED by `npm run sync-functions` from nudge/ - do not edit here.
// How a Pokémon picks its move when its ATB bar is full (plan 5.3), including the nudge (5.4).
// Everything here is deterministic and side-effect free except `pickMove`, which draws from the Rng.
import type { GameData, MoveData } from '../data/types.ts'
import type { Balance, MoveCategory } from './balance.ts'
import { calcDamage, stageMultiplier, typeEffectiveness } from './formulas.ts'
import { favoriteApplies, favoriteWeightMultiplier, nudgeAwayMultiplier } from './favorite.ts'
import { classifyMove, effectivePower, isDamaging, isInert, targetsSelf } from './moves.ts'
import { pickWeightedIndex, type Rng } from './rng.ts'
import type { Battler, ChoiceDebug, MoveChoice, PendingNudge } from './types.ts'

const CATEGORIES: MoveCategory[] = ['attack', 'defense', 'support']

/** Category weights from the nature (Battle Palace style): +Atk/SpA = attack-heavy, +Def/SpD = defense-heavy, +Spe = support-heavy. */
export function natureCategoryWeights(natureName: string, data: GameData, balance: Balance): Record<MoveCategory, number> {
  const nature = data.natures[natureName]
  const table = balance.CATEGORY_WEIGHTS
  let base = table.neutral
  switch (nature?.increased) {
    case 'attack': case 'spAttack': base = table.attack; break
    case 'defense': case 'spDefense': base = table.defense; break
    case 'speed': base = table.support; break
    default: break
  }
  const weights = { ...base }
  switch (nature?.decreased) {
    case 'attack': case 'spAttack': weights.attack *= balance.DECREASED_CATEGORY_MULT; break
    case 'defense': case 'spDefense': weights.defense *= balance.DECREASED_CATEGORY_MULT; break
    case 'speed': weights.support *= balance.DECREASED_CATEGORY_MULT; break
    default: break
  }
  return weights
}

/** 0..~1.3: how much the Pokémon's situational awareness counts. Scales with trust and trait. */
export function smartnessOf(battler: Battler, balance: Balance): number {
  const t = Math.max(0, Math.min(1, battler.trust / balance.TRUST_MAX))
  const base = balance.SMART_MIN + (balance.SMART_MAX - balance.SMART_MIN) * t
  return base * balance.TRAITS[battler.trait].smartMult
}

function expectedHits(move: MoveData): number {
  if (move.minHits == null || move.maxHits == null) return 1
  if (move.minHits === move.maxHits) return move.minHits
  return (2 * 3 + 3 * 3 + 4 + 5) / 8 // Gen 3 distribution for 2-5 hit moves
}

export function typeBoostFor(user: Battler, move: MoveData, balance: Balance): number {
  if (user.heldItem && !user.heldItemUsed && balance.TYPE_BOOST_ITEMS[user.heldItem] === move.type) return balance.TYPE_BOOST_MULT
  return 1
}

/** Expected damage of a move against a target (no crit, average roll). `typeExponent` > 1 makes type matchups count extra. */
export function estimateDamage(user: Battler, target: Battler, move: MoveData, data: GameData, balance: Balance, typeExponent = 1): number {
  if (!isDamaging(move)) return 0
  if (balance.OHKO_MOVES.includes(move.name)) return target.hp * 0.3
  const fixed = balance.FIXED_DAMAGE[move.name]
  if (fixed !== undefined) {
    const eff = typeEffectiveness(move.type, target.types, data.typeChart)
    return eff === 0 ? 0 : (fixed === 'level' ? user.level : fixed)
  }
  const power = effectivePower(move, balance)
  if (power == null) return 0
  const physical = move.damageClass === 'physical'
  const attackStat = physical ? user.stats.attack * stageMultiplier(user.stages.attack) : user.stats.spAttack * stageMultiplier(user.stages.spAttack)
  const defenseStat = physical ? target.stats.defense * stageMultiplier(target.stages.defense) : target.stats.spDefense * stageMultiplier(target.stages.spDefense)
  const effectiveness = typeEffectiveness(move.type, target.types, data.typeChart)
  const ranked = effectiveness === 0 ? 0 : Math.pow(effectiveness, typeExponent)
  const damage = calcDamage({
    level: user.level,
    power,
    attack: attackStat,
    defense: defenseStat,
    stab: user.types.includes(move.type),
    effectiveness: ranked,
    crit: false,
    burned: physical && user.status === 'burn',
    random: (1 + balance.DAMAGE_RANDOM_MIN) / 2,
    other: typeBoostFor(user, move, balance) * (user.favoriteMove === move.name ? balance.FAVORITE_POWER_MULT : 1),
  }, balance)
  const accuracy = move.accuracy == null ? 1 : move.accuracy / 100
  return damage * accuracy * expectedHits(move)
}

/** How useful a non-damaging move is right now, as a multiplier around 1. */
function statusMoveFactor(user: Battler, foe: Battler, move: MoveData, balance: Balance): number {
  if (isInert(move, balance)) return balance.INERT_MOVE_FACTOR
  const useless = balance.USELESS_STATUS_FACTOR
  const maxed = balance.MAXED_STAT_FACTOR
  let factor = 1

  if (move.healing > 0 || move.name === 'rest') {
    const fraction = user.hp / user.stats.hp
    const heal = fraction > 0.9 ? balance.HEAL_FULL_HP_FACTOR : 1 + balance.HEAL_LOW_HP_BOOST * Math.pow(1 - fraction, 2)
    factor *= move.name === 'rest' && user.status === 'sleep' ? useless : heal
  }

  if (move.statChanges.length > 0) {
    const onSelf = targetsSelf(move)
    const subject = onSelf ? user : foe
    let sum = 0
    for (const change of move.statChanges) {
      const stage = subject.stages[change.stat]
      const helpful = onSelf ? change.change > 0 : change.change < 0
      if (!helpful) {
        sum += 1
      } else if (onSelf) {
        sum += stage >= 6 ? maxed : Math.max(maxed, 1 - stage / 3)
      } else {
        sum += stage <= -6 ? maxed : Math.max(maxed, 1 + stage / 3)
      }
    }
    factor *= sum / move.statChanges.length
  }

  switch (move.ailment) {
    case 'paralysis': case 'sleep': case 'freeze': case 'burn': case 'poison': {
      const status = move.ailment
      const immune = {
        burn: ['fire'], poison: ['poison', 'steel'], paralysis: ['electric'], freeze: ['ice'], sleep: [] as string[],
      }[status].some(type => foe.types.includes(type as never))
      if (foe.status || immune || foe.fainted) factor *= useless
      break
    }
    case 'confusion':
      if (foe.confusionMs > 0) factor *= useless
      break
    case 'leech-seed':
      if (foe.seeded || foe.types.includes('grass')) factor *= useless
      break
    case 'protect':
      factor *= foe.atb > 600 ? 0.8 : 0.3
      break
    default:
      break
  }

  if (move.name === 'focus-energy' && user.critBonus >= 2) factor *= maxed
  if (move.name === 'haze' && Object.values(user.stages).every(s => s === 0) && Object.values(foe.stages).every(s => s === 0)) factor *= maxed
  if (move.name === 'belly-drum' && (user.hp / user.stats.hp < 0.6 || user.stages.attack >= 3)) factor *= maxed
  return factor
}

export interface ChoiceContext {
  self: Battler
  foe: Battler | null
  data: GameData
  balance: Balance
  nudge?: PendingNudge | null
}

/** The full probability distribution over this Pokémon's usable moves, with and without the nudge. */
export function computeChoice(ctx: ChoiceContext): ChoiceDebug {
  const { self, foe, data, balance } = ctx
  const trait = balance.TRAITS[self.trait]
  const smart = smartnessOf(self, balance)
  const usable = self.moves.map((instance, moveIndex) => ({ instance, moveIndex })).filter(entry => entry.instance.pp > 0)
  const emptyWeights = { attack: 0, defense: 0, support: 0 }

  if (usable.length === 0 || !foe) {
    return { moves: [], smart, nudgeStrength: 0, nudgedMoveIndex: null, categoryWeights: emptyWeights, struggle: true }
  }

  // Step 1 + 2: category of each move and the nature's category weights (adjusted for low-HP traits).
  const entries = usable.map(({ instance, moveIndex }) => {
    const move = data.moves[instance.move]
    return { instance, moveIndex, move, category: classifyMove(move, balance) }
  })
  const categoryWeights = natureCategoryWeights(self.nature, data, balance)
  if (trait.lowHpThreshold > 0 && self.hp / self.stats.hp < trait.lowHpThreshold) {
    categoryWeights.defense *= trait.lowHpDefenseMult
    categoryWeights.support *= trait.lowHpDefenseMult
  }
  const present = CATEGORIES.filter(c => entries.some(e => e.category === c))
  const presentTotal = present.reduce((sum, c) => sum + categoryWeights[c], 0) || 1
  const normalised: Record<MoveCategory, number> = { attack: 0, defense: 0, support: 0 }
  for (const c of present) normalised[c] = categoryWeights[c] / presentTotal

  // Step 3 + 4: situational factor and habits per move.
  const damages = entries.map(e => (e.category === 'attack' ? estimateDamage(self, foe, e.move, data, balance, trait.typeWeightExponent) : 0))
  const attackEntries = entries.filter(e => e.category === 'attack')
  const meanDamage = attackEntries.length ? attackEntries.reduce((sum, e) => sum + damages[entries.indexOf(e)], 0) / attackEntries.length : 0
  const meanPower = attackEntries.length ? attackEntries.reduce((sum, e) => sum + (effectivePower(e.move, balance) ?? 40), 0) / attackEntries.length : 0

  // `situational` is how useful the move is right now (damage relative to the other attacks, or an absolute usefulness for
  // status moves), pulled towards 1 when the Pokémon is not smart. `share` adds the habit bonus.
  const situational = entries.map((entry, i) => {
    let factor: number
    let exponent = smart
    if (entry.category === 'attack') {
      const immune = typeEffectiveness(entry.move.type, foe.types, data.typeChart) === 0
      if (immune) {
        factor = balance.IMMUNE_FACTOR
      } else if (trait.prefersPower) {
        factor = (effectivePower(entry.move, balance) ?? 40) / Math.max(1, meanPower)
        exponent = 1.5
      } else {
        factor = meanDamage > 0 ? damages[i] / meanDamage : 1
      }
      factor = Math.max(factor, 0.01)
    } else {
      factor = Math.max(statusMoveFactor(self, foe, entry.move, balance), 0.001)
    }
    return Math.pow(factor, exponent)
  })
  const shares = entries.map((entry, i) => {
    const habit = self.habits[entry.instance.move] ?? 0
    return situational[i] * (1 + Math.min(balance.HABIT_BONUS_CAP, balance.HABIT_WEIGHT * Math.log(1 + habit)))
  })

  // A category whose moves are all useless right now (or all very useful, e.g. healing at low HP) shifts weight accordingly.
  const categorySums: Record<MoveCategory, number> = { attack: 0, defense: 0, support: 0 }
  const categoryCounts: Record<MoveCategory, number> = { attack: 0, defense: 0, support: 0 }
  const categoryUsefulness: Record<MoveCategory, number> = { attack: 0, defense: 0, support: 0 }
  entries.forEach((entry, i) => {
    categorySums[entry.category] += shares[i]
    categoryCounts[entry.category]++
    categoryUsefulness[entry.category] += situational[i]
  })
  const adjusted: Record<MoveCategory, number> = { attack: 0, defense: 0, support: 0 }
  for (const c of present) {
    adjusted[c] = normalised[c] * Math.max(0.02, Math.min(4, categoryUsefulness[c] / categoryCounts[c]))
  }
  const adjustedTotal = present.reduce((sum, c) => sum + adjusted[c], 0) || 1
  for (const c of present) normalised[c] = adjusted[c] / adjustedTotal
  let weights = entries.map((entry, i) => normalised[entry.category] * (shares[i] / (categorySums[entry.category] || 1)))

  // The favorite move gets a weight bonus on top of nature and smartness (but not when it cannot hurt the target and the Pokémon is smart enough to know).
  const favoriteMults = entries.map((entry) => {
    if (!favoriteApplies(self, entry.instance.move, foe, data, balance)) return 1
    return favoriteWeightMultiplier(self.trait, balance)
  })
  weights = weights.map((w, i) => w * favoriteMults[i])

  // Playful Pokémon flatten the distribution.
  if (trait.flatten > 0) {
    const uniform = 1 / entries.length
    weights = weights.map(w => w * (1 - trait.flatten) + uniform * trait.flatten)
  }
  const total = weights.reduce((a, b) => a + b, 0) || 1
  const pAuto = weights.map(w => w / total)

  // Step 5: nudge.
  const nudgedEntryIndex = ctx.nudge ? entries.findIndex(e => e.moveIndex === ctx.nudge!.moveIndex) : -1
  let strength = nudgedEntryIndex >= 0 ? Math.max(0, Math.min(1, ctx.nudge!.strength)) : 0
  // Pulling a Pokémon away from its favorite is harder, as long as the favorite is usable and would have an effect.
  if (strength > 0 && self.favoriteMove && entries[nudgedEntryIndex].instance.move !== self.favoriteMove) {
    const favoriteUsable = entries.some(e => e.instance.move === self.favoriteMove && favoriteApplies(self, e.instance.move, foe, data, balance))
    if (favoriteUsable) strength *= nudgeAwayMultiplier(self.trait, balance)
  }
  const moves: MoveChoice[] = entries.map((entry, i) => ({
    moveIndex: entry.moveIndex,
    move: entry.instance.move,
    category: entry.category,
    weight: weights[i],
    pAuto: pAuto[i],
    pFinal: (1 - strength) * pAuto[i] + (i === nudgedEntryIndex ? strength : 0),
    expectedDamage: damages[i],
    favorite: entry.instance.move === self.favoriteMove,
    favoriteMult: favoriteMults[i],
  }))

  return {
    moves,
    smart,
    nudgeStrength: strength,
    nudgedMoveIndex: nudgedEntryIndex >= 0 ? ctx.nudge!.moveIndex : null,
    categoryWeights: normalised,
    struggle: false,
  }
}

/** Draws the move index (into `battler.moves`) from p_final, or -1 for Struggle. */
export function pickMove(rng: Rng, choice: ChoiceDebug): number {
  if (choice.struggle || choice.moves.length === 0) return -1
  const index = pickWeightedIndex(rng, choice.moves.map(m => m.pFinal))
  return choice.moves[Math.max(0, index)].moveIndex
}

/** Uniformly random usable move index (disobedience: "random move"), or -1 for Struggle. */
export function pickRandomUsableMove(rng: Rng, battler: Battler): number {
  const usable = battler.moves.map((m, i) => ({ m, i })).filter(entry => entry.m.pp > 0)
  if (usable.length === 0) return -1
  return usable[Math.floor(rng.next() * usable.length)].i
}
