// GENERATED by `npm run sync-functions` from nudge/ - do not edit here.
// The nudge: how strongly the n-th nudge of a battle pulls the Pokémon towards a move (plan 5.4).
import type { Balance } from './balance.ts'

/** Strength of the nudge with 0-based number `nudgeNumber` for a Pokémon with the given trust. */
export function nudgeStrengthFor(nudgeNumber: number, trust: number, balance: Balance): number {
  const curve = balance.NUDGE_CURVE
  const base = curve[Math.min(nudgeNumber, curve.length - 1)] ?? 0
  const t = Math.max(0, Math.min(1, trust / balance.TRUST_MAX))
  const trustMult = balance.NUDGE_TRUST_MIN_MULT + (balance.NUDGE_TRUST_MAX_MULT - balance.NUDGE_TRUST_MIN_MULT) * t
  return Math.min(balance.NUDGE_MAX_STRENGTH, base * trustMult)
}
