// GENERATED by `npm run sync-functions` from nudge/ - do not edit here.
// What happens to a Pokémon after a battle: HP/PP/status, XP and level-ups, new moves, evolution, habits and trust (4.2, 4.3, 5.5, 5.9).
import type { GameData } from '../data/types.ts'
import type { Balance } from './balance.ts'
import { favoriteSwitchMargin, favoriteThreshold } from './favorite.ts'
import { levelForXp, xpForLevel } from './formulas.ts'
import { maxHpOf, newMoveInstance, speciesOf } from './pokemon.ts'
import type { BattleOutcome, OwnedPokemon } from './types.ts'

export interface LevelUpInfo {
  uid: string
  from: number
  to: number
  /** Moves learned automatically (there was a free slot). */
  learned: string[]
  /** Moves the Pokémon wants to learn but has no free slot for: the UI asks which move to forget. */
  pendingMoves: string[]
  /** Set when a level-based evolution is now available. */
  evolveTo: number | null
}

export interface FavoriteEvent {
  uid: string
  kind: 'new' | 'switch'
  move: string
  /** The old favorite (switch only). */
  previous?: string
}

export interface OutcomeApplication {
  levelUps: LevelUpInfo[]
  favorites: FavoriteEvent[]
}

export function addTrust(pokemon: OwnedPokemon, delta: number, balance: Balance): void {
  pokemon.trust = Math.max(0, Math.min(balance.TRUST_MAX, Math.round(pokemon.trust + delta)))
}

export function rescaleHpAfterStatChange(data: GameData, pokemon: OwnedPokemon, oldMaxHp: number): void {
  const gained = maxHpOf(data, pokemon) - oldMaxHp
  pokemon.currentHp = Math.max(0, Math.min(maxHpOf(data, pokemon), pokemon.currentHp + Math.max(0, gained)))
}

/** Learnable level-up moves granted at exactly `level` that the Pokémon does not know yet. */
export function movesLearnedAtLevel(data: GameData, pokemon: OwnedPokemon, level: number): string[] {
  const species = speciesOf(data, pokemon)
  const known = new Set(pokemon.moves.map(m => m.move))
  return species.levelUpMoves.filter(e => e.level === level && data.moves[e.move] && !known.has(e.move)).map(e => e.move)
}

/** A level-based or "trade" evolution the Pokémon has reached (trades evolve at one fixed level here). Stones are separate: `stoneEvolution`. */
export function pendingEvolution(data: GameData, pokemon: Pick<OwnedPokemon, 'speciesId' | 'level'>, balance: Balance): number | null {
  const species = speciesOf(data, pokemon)
  const evolution = species.evolutions.find((e) => {
    if (e.item || !data.species[e.to]) return false
    if (e.trade) return pokemon.level >= balance.TRADE_EVOLUTION_LEVEL
    return pokemon.level >= e.minLevel
  })
  return evolution?.to ?? null
}

/** What an evolution stone does to this Pokémon: the species it turns into, or null when the stone has no effect on it. */
export function stoneEvolution(data: GameData, pokemon: Pick<OwnedPokemon, 'speciesId'>, item: string): number | null {
  const evolution = speciesOf(data, pokemon).evolutions.find(e => e.item === item && data.species[e.to])
  return evolution?.to ?? null
}

/** Called when a move is forgotten: forgetting the favorite hurts the relationship and blocks a new favorite for a while. */
export function loseFavorite(pokemon: OwnedPokemon, balance: Balance): void {
  delete pokemon.favoriteMove
  pokemon.favoriteCooldown = balance.FAVORITE_COOLDOWN_BATTLES
  addTrust(pokemon, -balance.FAVORITE_FORGET_TRUST_PENALTY, balance)
}

/**
 * Replaces move slot `replaceIndex` (or appends when there is room and replaceIndex is null). Habits for a forgotten move are dropped.
 * Returns true when the forgotten move was the Pokémon's favorite (trust penalty and cooldown are applied).
 */
export function learnMove(data: GameData, pokemon: OwnedPokemon, moveName: string, replaceIndex: number | null, balance: Balance): boolean {
  if (pokemon.moves.some(m => m.move === moveName)) return false
  const instance = newMoveInstance(data, moveName)
  if (replaceIndex === null) {
    if (pokemon.moves.length < balance.MAX_MOVES) pokemon.moves.push(instance)
    return false
  }
  const forgotten = pokemon.moves[replaceIndex]
  let lostFavorite = false
  if (forgotten) {
    delete pokemon.habits[forgotten.move]
    if (pokemon.favoriteMove === forgotten.move) {
      loseFavorite(pokemon, balance)
      lostFavorite = true
    }
  }
  pokemon.moves[replaceIndex] = instance
  return lostFavorite
}

/**
 * Checks whether a favorite forms or changes after a won battle. Progress is the habit value of each move.
 * A new favorite needs enough progress *and* enough trust; a rival move takes over when it is far enough ahead.
 */
export function updateFavorite(data: GameData, balance: Balance, pokemon: OwnedPokemon): FavoriteEvent | null {
  const known = new Set(pokemon.moves.map(m => m.move))
  if (pokemon.favoriteMove && !known.has(pokemon.favoriteMove)) delete pokemon.favoriteMove
  if (pokemon.trust < balance.FAVORITE_MIN_TRUST) return null
  const progress = (move: string) => pokemon.habits[move] ?? 0

  if (!pokemon.favoriteMove) {
    if ((pokemon.favoriteCooldown ?? 0) > 0) return null
    const threshold = favoriteThreshold(pokemon.trait, balance)
    const best = pokemon.moves.map(m => m.move).filter(m => data.moves[m] && progress(m) >= threshold).sort((a, b) => progress(b) - progress(a))[0]
    if (!best) return null
    pokemon.favoriteMove = best
    return { uid: pokemon.uid, kind: 'new', move: best }
  }

  const current = pokemon.favoriteMove
  const margin = favoriteSwitchMargin(pokemon.trait, balance)
  const rival = pokemon.moves.map(m => m.move).filter(m => m !== current && progress(m) >= progress(current) + margin).sort((a, b) => progress(b) - progress(a))[0]
  if (!rival) return null
  pokemon.habits[current] = Math.floor(progress(current) / 2)
  pokemon.favoriteMove = rival
  return { uid: pokemon.uid, kind: 'switch', move: rival, previous: current }
}

export function evolvePokemon(data: GameData, pokemon: OwnedPokemon, toSpeciesId: number): void {
  const oldMax = maxHpOf(data, pokemon)
  pokemon.speciesId = toSpeciesId
  rescaleHpAfterStatChange(data, pokemon, oldMax)
}

/** Grants XP and processes every level gained. Mutates the Pokémon. */
export function grantXp(data: GameData, balance: Balance, pokemon: OwnedPokemon, amount: number): LevelUpInfo | null {
  if (amount <= 0 || pokemon.level >= balance.MAX_LEVEL) return null
  const species = speciesOf(data, pokemon)
  const oldMax = maxHpOf(data, pokemon)
  const from = pokemon.level
  pokemon.xp += amount
  const to = levelForXp(data.growthRates, species.growthRate, pokemon.xp, balance.MAX_LEVEL)
  if (to === from) return null

  const learned: string[] = []
  const pendingMoves: string[] = []
  for (let level = from + 1; level <= to; level++) {
    pokemon.level = level
    addTrust(pokemon, balance.TRUST_LEVEL_UP, balance)
    for (const move of movesLearnedAtLevel(data, pokemon, level)) {
      if (pokemon.moves.length < balance.MAX_MOVES) {
        learnMove(data, pokemon, move, null, balance)
        learned.push(move)
      } else {
        pendingMoves.push(move)
      }
    }
  }
  pokemon.level = to
  rescaleHpAfterStatChange(data, pokemon, oldMax)
  return { uid: pokemon.uid, from, to, learned, pendingMoves, evolveTo: pendingEvolution(data, pokemon, balance) }
}

/** Applies a finished battle to the player's party (in place). */
export function applyBattleOutcome(data: GameData, balance: Balance, party: OwnedPokemon[], outcome: BattleOutcome): OutcomeApplication {
  const levelUps: LevelUpInfo[] = []
  const favorites: FavoriteEvent[] = []
  const won = outcome.result === 'win'
  for (const update of outcome.party) {
    const pokemon = party.find(p => p.uid === update.uid)
    if (!pokemon) continue
    pokemon.currentHp = update.currentHp
    pokemon.status = update.status ?? undefined
    pokemon.moves = update.moves.map(m => ({ ...m }))
    if (update.heldItem === null) delete pokemon.heldItem

    if (update.fainted) addTrust(pokemon, balance.TRUST_FAINT, balance)
    if (update.participated && (pokemon.favoriteCooldown ?? 0) > 0) pokemon.favoriteCooldown = (pokemon.favoriteCooldown ?? 0) - 1

    if (won && !update.fainted && update.participated) {
      addTrust(pokemon, balance.TRUST_WIN, balance)
      const cap = balance.HABIT_GAIN_CAP_PER_BATTLE
      const nudgeValue = balance.TRAITS[pokemon.trait].nudgedProgress
      for (const [move, used] of Object.entries(update.movesUsed)) {
        if (move === 'struggle' || !pokemon.moves.some(m => m.move === move)) continue
        // Uses that happened because a nudge was followed count extra (x2, x3 for loyal Pokémon), with their own cap.
        const nudged = Math.min(update.nudgedMoves?.[move] ?? 0, used)
        pokemon.habits[move] = (pokemon.habits[move] ?? 0) + Math.min(used - nudged, cap) + Math.min(nudged, cap) * nudgeValue
      }
      const favorite = updateFavorite(data, balance, pokemon)
      if (favorite) favorites.push(favorite)
      if (update.followedNudge) {
        addTrust(pokemon, balance.TRUST_NUDGE_WIN * balance.TRAITS[pokemon.trait].nudgeTrustBonusMult, balance)
      }
    }

    const gained = outcome.xp[pokemon.uid] ?? 0
    const info = grantXp(data, balance, pokemon, gained)
    if (info) levelUps.push(info)
  }
  return { levelUps, favorites }
}

/** Pokémon Center: full HP, no status, full PP, +1 trust. */
export function healPokemon(data: GameData, balance: Balance, pokemon: OwnedPokemon, withTrust = true): void {
  pokemon.currentHp = maxHpOf(data, pokemon)
  pokemon.status = undefined
  for (const move of pokemon.moves) move.pp = move.maxPp
  if (withTrust) addTrust(pokemon, balance.TRUST_CENTER, balance)
}

export { xpForLevel }
