// GENERATED by `npm run sync-functions` from nudge/ - do not edit here.
// The version of the battle rules, saved with every online match (PLAN-4 2.4). Bump it whenever a change to the engine or the data can change the
// outcome of a battle, so old replays and results can be told apart. Replays play the saved event log, so they keep working regardless.
export const ENGINE_VERSION = '1'
