import type { MapDef } from '../types'

// A long north-south route: tall grass with Pidgey/Rattata, two trainers.
export const route1: MapDef = {
  id: 'route1',
  name: 'Väg 1',
  music: 'route1',
  encounterTable: 'route1',
  tiles: [
    '######==######',
    '#.....==.....#',
    '#.....==...#.#',
    '#,,,,.==.....#',
    '#,,,,.==.,,,,#',
    '#,,,,#==.,,,,#',
    '#,,,,.==.,,,,#',
    '#,,,,.==.,,,,#',
    '#,,,,==..,,,,#',
    '#....==......#',
    '#.#..==....o.#',
    '##...==......#',
    '#..#.==.....##',
    '#....==...#..#',
    '#,,,.==......#',
    '#,,,==......##',
    '#,,,==.......#',
    '#,,,==...,,,,#',
    '#,,,==...,,,,#',
    '#,,,==...,,,,#',
    '#...==...,,,,#',
    '#..o==...,,,,#',
    '#.#.==...,,,,#',
    '#....==......#',
    '#,,,,==..,,,,#',
    '#,,,,==..,,,,#',
    '#,,,,==..,,,,#',
    '#,,,,==..,,,,#',
    '#,,,,.==.,,,,#',
    '#...#.==oS...#',
    '#.#...==...#.#',
    '######==######',
  ],
  warps: [
    { x: 6, y: 31, to: 'hemstad', toX: 9, toY: 1, facing: 'down' },
    { x: 7, y: 31, to: 'hemstad', toX: 10, toY: 1, facing: 'down' },
    { x: 6, y: 0, to: 'skogen', toX: 11, toY: 28, facing: 'up' },
    { x: 7, y: 0, to: 'skogen', toX: 12, toY: 28, facing: 'up' },
  ],
  npcs: [
    {
      id: 'r1-vandrare', x: 8, y: 28, facing: 'left', look: 'hiker',
      dialog: ['Högt gräs! Där gömmer sig vilda Pokémon.', 'Försvaga dem först, så går de lättare att fånga med en Poké Ball.'],
    },
  ],
  trainers: [
    { id: 'r1-kalle', x: 7, y: 20, facing: 'left', sight: 3 },
    { id: 'r1-lisa', x: 4, y: 9, facing: 'right', sight: 3 },
  ],
  signs: [{ x: 9, y: 29, text: ['VÄG 1', 'Hemstad söderut. Viridianskogen norrut.'] }],
}
