// GENERATED by `npm run sync-functions` from nudge/ - do not edit here.
// Picking an opponent for a bracket match (PLAN-4 2.5): another player's current team in the same bracket, close in rating, random among the closest.
import type { Rng } from '../engine/rng.ts'

export interface Candidate {
  userId: string
  rating: number
}

/** Opponents within this many rating points are preferred. */
export const MATCH_RATING_WINDOW = 150
/** The closest this many are drawn from. */
export const MATCH_POOL_SIZE = 5

/**
 * Chooses an opponent for `self` among `candidates` (the other players with a team in the bracket; the player themself is never chosen even if listed).
 * The pool is the closest few in rating, within the window if there are any there. Opponents faced recently are avoided when someone else is available.
 */
export function pickOpponent<T extends Candidate>(candidates: T[], selfId: string, selfRating: number, recentOpponents: string[], rng: Rng): T | null {
  const others = candidates.filter(c => c.userId !== selfId)
  if (others.length === 0) return null
  const fresh = others.filter(c => !recentOpponents.includes(c.userId))
  const base = fresh.length > 0 ? fresh : others
  const byDistance = [...base].sort((a, b) => Math.abs(a.rating - selfRating) - Math.abs(b.rating - selfRating) || (a.userId < b.userId ? -1 : 1))
  const inWindow = byDistance.filter(c => Math.abs(c.rating - selfRating) <= MATCH_RATING_WINDOW)
  const pool = (inWindow.length > 0 ? inWindow : byDistance).slice(0, MATCH_POOL_SIZE)
  return pool[Math.floor(rng.next() * pool.length)] ?? null
}
