// GENERATED by `npm run sync-functions` from nudge/ - do not edit here.
// The team a player sends in (PLAN-4 2.4): a snapshot of 3 Pokémon that the server validates and turns into real Pokémon. Stats are never taken from the
// client: they are computed from the species, level, IVs and nature. Pure TypeScript, shared by the game and the Edge Functions.
import type { GameData } from '../data/types.ts'
import type { Balance, TraitId } from '../engine/balance.ts'
import { createPokemon, maxHpOf } from '../engine/pokemon.ts'
import { createRng } from '../engine/rng.ts'
import type { OwnedPokemon } from '../engine/types.ts'
import { itemInfo } from '../game/items.ts'
import { bracketRange, TEAM_SIZE } from './brackets.ts'

export interface PokemonSnapshot {
  /** The instance id (the same Pokémon cannot be in a team twice). */
  uid: string
  speciesId: number
  nickname?: string
  level: number
  ivs: { hp: number, attack: number, defense: number, spAttack: number, spDefense: number, speed: number }
  nature: string
  trait: string
  trust: number
  /** Move names (1-4). */
  moves: string[]
  heldItem?: string
  /** Learned habits and the favorite move: they shape how the Pokémon chooses, so they are part of the team. */
  habits: Record<string, number>
  favoriteMove?: string
}

const KEYS = ['uid', 'speciesId', 'nickname', 'level', 'ivs', 'nature', 'trait', 'trust', 'moves', 'heldItem', 'habits', 'favoriteMove']
const IV_KEYS = ['hp', 'attack', 'defense', 'spAttack', 'spDefense', 'speed']
const MAX_HABIT = 1000
const MAX_NICKNAME = 12

/** What the client sends: a snapshot of a Pokémon it owns. */
export function snapshotOf(pokemon: OwnedPokemon): PokemonSnapshot {
  return {
    uid: pokemon.uid,
    speciesId: pokemon.speciesId,
    ...(pokemon.nickname ? { nickname: pokemon.nickname } : {}),
    level: pokemon.level,
    ivs: { ...pokemon.ivs },
    nature: pokemon.nature,
    trait: pokemon.trait,
    trust: pokemon.trust,
    moves: pokemon.moves.map(m => m.move),
    ...(pokemon.heldItem ? { heldItem: pokemon.heldItem } : {}),
    habits: { ...pokemon.habits },
    ...(pokemon.favoriteMove ? { favoriteMove: pokemon.favoriteMove } : {}),
  }
}

const isInt = (v: unknown): v is number => typeof v === 'number' && Number.isInteger(v)

/** The species and everything it evolved from (a Charizard still knows what Charmander learned). */
function lineOf(data: GameData, speciesId: number): number[] {
  const line = [speciesId]
  const seen = new Set(line)
  for (let i = 0; i < line.length; i++) {
    for (const s of Object.values(data.species)) {
      if (!seen.has(s.id) && s.evolutions.some(e => e.to === line[i])) {
        seen.add(s.id)
        line.push(s.id)
      }
    }
  }
  return line
}

/** The moves a Pokémon of `level` can legally know: learned by level-up (it or an earlier form) or taught by a TM. */
export function legalMoves(data: GameData, speciesId: number, level: number): Set<string> {
  const legal = new Set<string>()
  for (const id of lineOf(data, speciesId)) {
    const species = data.species[id]
    for (const m of species.levelUpMoves) if (m.level <= level) legal.add(m.move)
    for (const m of species.tmMoves) legal.add(m)
  }
  return legal
}

export type TeamValidation = { ok: true, team: PokemonSnapshot[] } | { ok: false, errors: string[] }

/**
 * Checks a submitted team: exactly 3 Pokémon, all levels inside the bracket, species, IVs 0-31, nature, trait, trust 0-255, legal moves, held item,
 * no unknown fields (no made-up stats) and no instance twice. Returns every problem found, in Swedish.
 */
export function validateTeam(data: GameData, balance: Balance, input: unknown, bracket: string): TeamValidation {
  const errors: string[] = []
  const range = bracketRange(bracket)
  if (!range) return { ok: false, errors: [`Okänd nivågräns: ${bracket}`] }
  if (!Array.isArray(input) || input.length !== TEAM_SIZE) return { ok: false, errors: [`Ett lag ska ha exakt ${TEAM_SIZE} Pokémon.`] }

  const team: PokemonSnapshot[] = []
  const uids = new Set<string>()
  const species = new Set<number>()
  input.forEach((raw: unknown, index) => {
    const label = `Pokémon ${index + 1}`
    const fail = (message: string) => errors.push(`${label}: ${message}`)
    if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return fail('felaktigt format.')
    const p = raw as Record<string, unknown>
    const extra = Object.keys(p).filter(k => !KEYS.includes(k))
    if (extra.length) fail(`okända fält (${extra.join(', ')}). Stats räknas ut av servern.`)

    if (typeof p.uid !== 'string' || p.uid.length === 0 || p.uid.length > 64) fail('saknar giltigt id.')
    else if (uids.has(p.uid)) fail('samma Pokémon finns två gånger i laget.')
    else uids.add(p.uid)

    if (!isInt(p.speciesId) || !data.species[p.speciesId]) return fail('okänd art.')
    const speciesId = p.speciesId
    const speciesName = data.species[speciesId].displayName
    if (!balance.PVP_ALLOW_DUPLICATE_SPECIES && species.has(speciesId)) fail(`${speciesName} får bara finnas en gång i laget.`)
    species.add(speciesId)

    if (!isInt(p.level) || p.level < range.min || p.level > range.max) fail(`${speciesName} har nivå ${String(p.level)}, men nivågränsen är ${range.min}-${range.max}.`)
    const level = isInt(p.level) ? p.level : 1

    const ivs = p.ivs as Record<string, unknown> | undefined
    if (!ivs || typeof ivs !== 'object' || IV_KEYS.some(k => !isInt(ivs[k]) || (ivs[k] as number) < 0 || (ivs[k] as number) > balance.IV_MAX) || Object.keys(ivs).some(k => !IV_KEYS.includes(k))) {
      fail(`${speciesName} har ogiltiga IV-värden (0-${balance.IV_MAX}).`)
    }
    if (typeof p.nature !== 'string' || !data.natures[p.nature]) fail(`${speciesName} har en ogiltig natur.`)
    if (typeof p.trait !== 'string' || !(p.trait in balance.TRAITS)) fail(`${speciesName} har ett ogiltigt drag.`)
    if (!isInt(p.trust) || p.trust < 0 || p.trust > balance.TRUST_MAX) fail(`${speciesName} har ogiltigt förtroende (0-${balance.TRUST_MAX}).`)

    const moves = p.moves
    if (!Array.isArray(moves) || moves.length < 1 || moves.length > balance.MAX_MOVES || moves.some(m => typeof m !== 'string') || new Set(moves).size !== moves.length) {
      fail(`${speciesName} måste ha 1-${balance.MAX_MOVES} olika attacker.`)
    } else {
      const legal = legalMoves(data, speciesId, level)
      for (const m of moves as string[]) {
        if (!data.moves[m]) fail(`${speciesName} har en okänd attack (${m}).`)
        else if (!legal.has(m)) fail(`${speciesName} kan inte kunna ${data.moves[m].displayName}.`)
      }
    }

    if (p.heldItem !== undefined) {
      let holdable = false
      try {
        holdable = typeof p.heldItem === 'string' && itemInfo(data, p.heldItem).holdable
      } catch {
        holdable = false
      }
      if (!holdable) fail(`${speciesName} håller ett ogiltigt föremål.`)
    }
    if (p.nickname !== undefined && (typeof p.nickname !== 'string' || p.nickname.length > MAX_NICKNAME)) fail('ogiltigt smeknamn.')

    const habits = p.habits as Record<string, unknown> | undefined
    if (!habits || typeof habits !== 'object' || Array.isArray(habits)) fail('saknar vanor.')
    else {
      for (const [move, value] of Object.entries(habits)) {
        if (!data.moves[move] || typeof value !== 'number' || !Number.isFinite(value) || value < 0 || value > MAX_HABIT) fail(`ogiltig vana (${move}).`)
      }
    }
    if (p.favoriteMove !== undefined && (typeof p.favoriteMove !== 'string' || !Array.isArray(moves) || !(moves as string[]).includes(p.favoriteMove))) fail('favoritattacken måste vara en av attackerna.')

    team.push(raw as PokemonSnapshot)
  })
  return errors.length ? { ok: false, errors } : { ok: true, team }
}

/** Turns a validated snapshot into a fresh Pokémon: full HP, full PP, no status, stats from the species data. */
export function buildPokemon(data: GameData, balance: Balance, snap: PokemonSnapshot): OwnedPokemon {
  const pokemon = createPokemon({
    data, balance, rng: createRng(1), speciesId: snap.speciesId, level: snap.level, trust: snap.trust, nature: snap.nature, trait: snap.trait as TraitId,
    ivs: snap.ivs, moves: snap.moves, heldItem: snap.heldItem, nickname: snap.nickname, originalTrainer: '',
  })
  pokemon.uid = snap.uid
  pokemon.habits = { ...snap.habits }
  if (snap.favoriteMove) pokemon.favoriteMove = snap.favoriteMove
  pokemon.currentHp = maxHpOf(data, pokemon)
  return pokemon
}

export function buildTeam(data: GameData, balance: Balance, team: PokemonSnapshot[]): OwnedPokemon[] {
  return team.map(p => buildPokemon(data, balance, p))
}
