// Copies the code the Edge Functions share with the game (the battle engine, the data and the server modules) to supabase/functions/_shared/nudge/ and adjusts
// the imports for Deno (explicit `.ts` extensions, `with { type: 'json' }` on JSON). One source of truth: edit nudge/engine, nudge/data and nudge/server,
// then run `npm run sync-functions`. A test fails when the copy is out of date. The engine has no Node or browser dependencies, so it runs unchanged.
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const nudge = join(root, 'nudge')
export const SHARED_DIR = join(root, 'supabase', 'functions', '_shared', 'nudge')

/** Directories (relative to nudge/) copied whole, and single files. */
const DIRS = ['engine', 'server']
const FILES = ['data/index.ts', 'data/types.ts', 'data/pokemon.json', 'data/moves.json', 'data/types.json', 'data/natures.json', 'data/growth-rates.json', 'data/items.json', 'game/items.ts']
const HEADER = '// GENERATED by `npm run sync-functions` from nudge/ - do not edit here.\n'

/** Makes the relative imports of a TypeScript file Deno-style. */
export function toDeno(source: string): string {
  return source.replace(/(from\s+|import\s+)(['"])(\.{1,2}\/[^'"]+)\2/g, (match, lead: string, quote: string, path: string) => {
    if (path.endsWith('.json')) return `${lead}${quote}${path}${quote} with { type: 'json' }`
    if (/\.(ts|js|json)$/.test(path)) return match
    return `${lead}${quote}${path}.ts${quote}`
  })
}

function listFiles(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap(e => (e.isDirectory() ? listFiles(join(dir, e.name)) : e.name.endsWith('.ts') ? [join(dir, e.name)] : []))
}

/** All files of the shared copy: path (relative to SHARED_DIR) -> content. */
export function buildSharedFiles(): Map<string, string> {
  const out = new Map<string, string>()
  const sources = [...DIRS.flatMap(d => listFiles(join(nudge, d)).map(f => relative(nudge, f))), ...FILES]
  for (const rel of sources) {
    const text = readFileSync(join(nudge, rel), 'utf8')
    out.set(rel, rel.endsWith('.json') ? text : HEADER + toDeno(text))
  }
  return out
}

function main() {
  rmSync(SHARED_DIR, { recursive: true, force: true })
  const files = buildSharedFiles()
  for (const [rel, content] of files) {
    const target = join(SHARED_DIR, rel)
    mkdirSync(dirname(target), { recursive: true })
    writeFileSync(target, content)
  }
  console.log(`Copied ${files.size} files to supabase/functions/_shared/nudge/`)
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) main()
